In [220]:
import numpy as np

In [221]:
np

<module 'numpy' from 'c:\\Users\\Husnain\\miniconda3\\envs\\ml_env\\lib\\site-packages\\numpy\\__init__.py'>

**NumPy arrays**

Creating arrays
- `np.zeros`
- `np.ones`
- `np.full`
- `np.repeat`
- `np.array`
- `np.arange`

In [222]:
zeros=np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [223]:
ones=np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [224]:
array=np.full(5,512)
array

array([512, 512, 512, 512, 512])

In [225]:
a=np.array([512, 512, 512, 512, 512])
a[3]=514
a

array([512, 512, 512, 514, 512])

In [226]:
array=np.repeat(4,5)
array

array([4, 4, 4, 4, 4])

In [227]:
array=np.repeat([1,2,1],3)
array

array([1, 1, 1, 2, 2, 2, 1, 1, 1])

In [228]:
array=np.repeat([1,2],[4,1])
array

array([1, 1, 1, 1, 2])

Accessing the element of an array by index:



In [229]:
ele=array[1]
print(ele)

1


Accessing multuple elements of an array by a list of indices:



In [230]:
array[[4,2,0]]

array([2, 1, 1])

Assignment:



In [231]:
array[2]=512
array

array([  1,   1, 512,   1,   2])

Creating an array from a list with integers:



In [232]:
elements=[512,514,572,100]
array=np.array(elements)
array

array([512, 514, 572, 100])

Specifying the type of elements:



In [233]:
zeros=np.zeros(5,dtype=np.uint8)
zeros

array([0, 0, 0, 0, 0], dtype=uint8)

np.arange for creating ranges:



In [234]:
for i in np.arange(5):
    print(i)

0
1
2
3
4


In [235]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

Linspace - for creating an array with elements from start till end of a certain size:



In [236]:
threshold=np.linspace(5,100,6)
threshold

array([  5.,  24.,  43.,  62.,  81., 100.])

In [237]:
np.linspace(0,150,6)

array([  0.,  30.,  60.,  90., 120., 150.])

**Multi-dimensional NumPy arrays**\
Specify the shape with a tuple:



In [238]:
zeros=np.zeros((5,2),dtype=np.float32)
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [239]:
print(zeros.shape)

(5, 2)


In [240]:
numbers = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

numbers = np.array(numbers)
numbers

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [241]:
print(numbers[0,1])

2


Assignment: use a tuple (row index, column index)



In [242]:
numbers[1,2]=512
numbers

array([[  1,   2,   3],
       [  4,   5, 512],
       [  7,   8,   9]])

In [243]:
numbers[0]

array([1, 2, 3])

In [244]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [245]:
n=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [246]:
n[2,2]

np.int64(9)

In [247]:
n[2,2]=512
n

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8, 512]])

In [248]:
n[2]

array([  7,   8, 512])

Slicing: getting a column:



In [249]:
n[:,1]

array([2, 5, 8])

Assigning a row:



In [250]:
n[0]=[0,0,0]


Assigning a column:



In [251]:
n[:,1]=[12,14,72]
n

array([[  0,  12,   0],
       [  4,  14,   6],
       [  7,  72, 512]])

In [252]:
n[2,2]=514
n

array([[  0,  12,   0],
       [  4,  14,   6],
       [  7,  72, 514]])

**Randomly Generated Arrays**\
Uniform random numbers between 0 and 1 of shape (5, 2):



In [253]:
np.random.rand(4,3)

array([[0.4203678 , 0.33033482, 0.20464863],
       [0.61927097, 0.29965467, 0.26682728],
       [0.62113383, 0.52914209, 0.13457995],
       [0.51357812, 0.18443987, 0.78533515]])

Set seed for reproducibility:



In [254]:
np.random.seed(2)
np.random.rand(4,3)

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467],
       [0.26682728, 0.62113383, 0.52914209]])

In [255]:
np.random.seed(2)
np.random.randn(4,3)

array([[-0.41675785, -0.05626683, -2.1361961 ],
       [ 1.64027081, -1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809, -1.05795222],
       [-0.90900761,  0.55145404,  2.29220801]])

Random integers between 12 and 71 (72 is not included)



In [256]:
np.random.seed(2)
np.random.randint(low=12,high=72,size=(5,2))

array([[52, 27],
       [57, 20],
       [34, 55],
       [30, 23],
       [52, 19]], dtype=int32)

**Element-wise Operations**


In [257]:
rng=np.arange(5)
rng

array([0, 1, 2, 3, 4])

Every item in the array is multiplied by 2:



In [258]:
rng*5

array([ 0,  5, 10, 15, 20])

In [259]:
(rng - 1) * 3 / 2 + 1


array([-0.5,  1. ,  2.5,  4. ,  5.5])

Adding one array with another



In [260]:
np.random.seed(2)
noise = 0.01 * np.random.rand(5)
noise

array([0.00435995, 0.00025926, 0.00549662, 0.00435322, 0.00420368])

In [261]:
numbers = np.arange(5)
numbers

array([0, 1, 2, 3, 4])

In [262]:
result = numbers + noise
result

array([0.00435995, 1.00025926, 2.00549662, 3.00435322, 4.00420368])

In [263]:
result.round(4)

array([0.0044, 1.0003, 2.0055, 3.0044, 4.0042])

Two ways to square each element:

- element-wise multiplication with itself
- the power operator (**)

In [264]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [265]:
square = pred * pred
square

array([0.1936, 0.0009, 0.3025])

In [266]:
square = pred ** 2
square

array([0.1936, 0.0009, 0.3025])

Other element-wise operations:

- `exp`
- `log`
- `sqrt`

In [267]:
np.exp(square)

array([1.21361074, 1.00090041, 1.35323768])

In [268]:
np.log(pred)


array([-0.82098055, -3.5065579 , -0.597837  ])

In [269]:
np.sqrt(square)

array([0.44, 0.03, 0.55])

**Comparison Operations**

In [270]:
np.random.seed(2)
pred=np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [271]:
result = pred >= 0.5
result

array([False, False,  True])

In [272]:
np.random.seed(2)
pred1 = np.random.rand(3).round(2)
pred2 = np.random.rand(3).round(2)
pred1 >= pred2


array([ True, False,  True])

In [273]:
np.random.seed(2)
pred1 = np.random.rand(3) >= 0.3
pred1


array([ True, False,  True])

In [274]:
pred2 = np.random.rand(3) >= 0.4
pred2

array([ True,  True, False])

**Logical operations**


In [275]:
pred1 & pred2


array([ True, False, False])

In [276]:
pred1 | pred2


array([ True,  True,  True])

**Summarizing Operations**

Summarizing operations process and array and return a single number

In [277]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred_sum = pred.sum()
pred_sum

np.float64(1.02)

In [278]:
print('min = %.2f' % pred.min())
print('mean = %.2f' % pred.mean())
print('max = %.2f' % pred.max())
print('std = %.2f' % pred.std())

min = 0.03
mean = 0.34
max = 0.55
std = 0.22


For two-dimentional array it works in the same way:



In [279]:
np.random.seed(2)
matrix = np.random.rand(4, 3).round(2)
matrix

array([[0.44, 0.03, 0.55],
       [0.44, 0.42, 0.33],
       [0.2 , 0.62, 0.3 ],
       [0.27, 0.62, 0.53]])

In [280]:
matrix.max()

np.float64(0.62)

But we can specify the axis along which we apply the summarizing operation

- `axis=1` - apply to each rows
- `axis=0` - apply to each column

In [281]:
matrix.max(axis=1)


array([0.55, 0.44, 0.62, 0.62])

In [282]:
matrix.max(axis=0)


array([0.44, 0.62, 0.55])

In [283]:
matrix.sum(axis=1)


array([1.02, 1.19, 1.12, 1.42])

**Sorting**


In [284]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

Creaters a new array:



In [285]:
np.sort(pred)

array([0.03, 0.44, 0.44, 0.55])

In [286]:
pred

array([0.44, 0.03, 0.55, 0.44])

Sorts in place:



In [287]:
pred.sort()

In [288]:
pred

array([0.03, 0.44, 0.44, 0.55])

Argsort - instead of sorting, return the indexes of the array in sorted order



In [289]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [291]:
idx=pred.argsort()
idx

array([1, 0, 3, 2])

In [292]:
pred[idx]

array([0.03, 0.44, 0.44, 0.55])

**Reshaping**

The shape of an array cound be changed

In [294]:
rng=np.arange(12)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [298]:
rng.shape

(12,)

In [297]:
rng.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [299]:
rng.reshape(4, 3, order='F')


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

But number of rows x columns should be equal to the total number of elements



In [300]:
rng.reshape(4, 4)


ValueError: cannot reshape array of size 12 into shape (4,4)

In [301]:
vec = np.arange(3)
vec

array([0, 1, 2])

In [302]:
mat = np.arange(6).reshape(3, 2)
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

Putting mulitple arrays together:

- `concatenate`
- `hstack`
- `vstack`
- `column_stack`

In [303]:
np.concatenate([vec,vec])

array([0, 1, 2, 0, 1, 2])

In [304]:
np.hstack([vec, vec])


array([0, 1, 2, 0, 1, 2])

In [305]:
np.hstack([mat,mat])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [306]:
np.concatenate([mat,mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [307]:
vec

array([0, 1, 2])

In [308]:
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [309]:
np.column_stack([vec,mat])

array([[0, 0, 1],
       [1, 2, 3],
       [2, 4, 5]])

In [310]:
np.vstack([vec,vec])

array([[0, 1, 2],
       [0, 1, 2]])

In [311]:
np.vstack([mat, mat])


array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

Transpose

In [312]:
mat.T


array([[0, 2, 4],
       [1, 3, 5]])

In [313]:
np.vstack([vec, mat.T])


array([[0, 1, 2],
       [0, 2, 4],
       [1, 3, 5]])

**Slicing**

Taking a part of the array

In [314]:
mat = np.arange(15).reshape(5, 3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [316]:
mat[:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [315]:
mat[1:3,:]

array([[3, 4, 5],
       [6, 7, 8]])

In [317]:
mat[1:3,:2]

array([[3, 4],
       [6, 7]])

In [318]:
mat[:,:2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [320]:
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [321]:
mat[[3, 0, 1]]


array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [322]:
mat[:, 0] % 2 == 1


array([False,  True, False,  True, False])

In [323]:
mat[mat[:, 0] % 2 == 1]


array([[ 3,  4,  5],
       [ 9, 10, 11]])

**Linear Algebra**

**Multiplication**

Vector-vector multiplication

In [324]:
u=np.array([0,1,2])
v=np.array([1,2,3])
u.dot(v)

np.int64(8)

Matrix-vector multiplication



In [ ]:
X = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3]
])

In [326]:
X.dot(u)

array([5, 8, 9])

In [327]:
U = np.array([
    [4, 5, 6],
    [5, 6, 7],
    [6, 7, 8]
])
X.dot(U)

array([[17, 20, 23],
       [32, 38, 44],
       [41, 49, 57]])

**Inverse**

To inverse a matrix, use inv function from linalg package

In [328]:
A = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 3]
])

In [330]:
Ainv=np.linalg.inv(A)
Ainv

array([[-3.,  3., -1.],
       [ 3., -4.,  2.],
       [-1.,  2., -1.]])

In [331]:
A.dot(Ainv)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

B is not invertible ("singular"):

In [332]:
B = np.array([
    [0, 1, 1],
    [1, 2, 3],
    [2, 3, 5]
])

np.linalg.inv(B)

LinAlgError: Singular matrix

Note: When you need to solve Ax = b, you don't really to compute the inverse. You can use solve:



In [333]:
b = np.array([1, 2, 3])


In [334]:
x = np.linalg.solve(A, b)
x


array([0., 1., 0.])

In [335]:
A.dot(x)

array([1., 2., 3.])